format_version: 10
pipelines:
  12-factor-app:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-7c0a7db:
        git: https://github.com/andhikayusup/12-factor-apps
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                command: ./gradlew
                run_if: passed
