name: 'Hello World Action'
description: 'A simple GitHub Action to print "Hello, World!"'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
runs:
  using: 'node16'
  main: 'index.js'
