/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factor.apps;

import com.google.gson.Gson;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import spark.Spark;
import java.util.Map;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    @BeforeAll
    public static void setUp() {
        // Start the Spark application
        App.main(null);
        Spark.awaitInitialization();
    }

    @AfterAll
    public static void tearDown() {
        // Stop the Spark application
        Spark.stop();
    }

    @Test
    public void testHelloEndpoint() throws Exception {
        HttpResponse<String> jsonResponse = Unirest.get("http://localhost:4567/hello")
                .header("accept", "application/json")
                .asString();

        assertEquals(200, jsonResponse.getStatus());

        Gson gson = new Gson();
        Map<String, String> resultMap = gson.fromJson(jsonResponse.getBody(), Map.class);

        assertEquals("Hello, World!", resultMap.get("message"));
    }
}
