name: Java CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Test with Gradle
      run: ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{secrets.AWS_ECR_REGISTRY_URI}}

      - name: Build and push Docker image
        run: |
          docker build -t ${{secrets.AWS_ECR_REGISTRY_URI}}/12fa-apps:latest .
          docker push ${{secrets.AWS_ECR_REGISTRY_URI}}/12fa-apps:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Hello World Action
        uses: ./.github/actions/deploy
        with:
          who-to-greet: 'Mona the Octocat'
          public-key: ${{ secrets.PUBLIC_KEY }}

