name: Java CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Gradle 8
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '8.0'

    - name: Test with Gradle
      run: ./gradlew test --info
